//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG_Test_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class IG_Rating_Login_Service
    {
        public int id { get; set; }
        public string loginToken { get; set; }
        public string serviceCode { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> ratingPoint { get; set; }
        public string feedback { get; set; }

        [ForeignKey("loginToken")]

        public virtual IG_Login_Service IG_Login_Service { get; set; }
        [ForeignKey("serviceCode")]
        public virtual IG_Service IG_Service { get; set; }
    }
}
